import React, { useEffect, useState } from "react";
import { toast } from "react-toastify";
import "../css/JoinCreateRoom.css";

// A meeting ID typed by a person, not generated by uuid(), is shared as
// the literal Socket.IO room name — keep it to characters that are safe in
// a URL and can't collide with formatting weirdness.
const CUSTOM_ID_RE = /^[a-zA-Z0-9-]{4,40}$/;

const JoinCreateRoom = ({ uuid, setUser, setRoomJoined, account, onLogout, onLoginClick, onSignupClick }) => {
  const [roomId, setRoomId] = useState(uuid());
  const [idMode, setIdMode] = useState("random"); // "random" | "custom"
  const [customIdError, setCustomIdError] = useState("");
  const [name, setName] = useState(account?.name || "");
  const [boardName, setBoardName] = useState("");
  const [joinName, setJoinName] = useState(account?.name || "");
  const [joinRoomId, setJoinRoomId] = useState("");
  const [copied, setCopied] = useState(false);
  const [hoveredCard, setHoveredCard] = useState(null);
  const [prefilled, setPrefilled] = useState(false);

  // If someone opens an invite link like "?room=<id>", drop the room ID
  // straight into the Join card so all they have to do is add their name.
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const roomFromLink = params.get("room");
    if (roomFromLink) {
      setJoinRoomId(roomFromLink);
      setPrefilled(true);
      toast.info("Room ID filled in from your invite link — just add your name.");
    }
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(roomId);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleModeChange = (mode) => {
    setIdMode(mode);
    setCustomIdError("");
    if (mode === "random") setRoomId(uuid());
    else setRoomId("");
  };

  const handleCustomIdChange = (value) => {
    setRoomId(value.trim());
    if (value.trim() && !CUSTOM_ID_RE.test(value.trim())) {
      setCustomIdError("4-40 characters: letters, numbers, and dashes only.");
    } else {
      setCustomIdError("");
    }
  };

  const handleCreateSubmit = (e) => {
    e.preventDefault();
    if (!name.trim()) {
      toast.error("Please enter your name!");
      return;
    }
    if (idMode === "custom" && (!roomId.trim() || !CUSTOM_ID_RE.test(roomId.trim()))) {
      toast.error("Please enter a valid meeting ID (4-40 letters, numbers, or dashes).");
      return;
    }

    setUser({
      roomId,
      userId: uuid(),
      userName: name.trim(),
      boardName: boardName.trim() || roomId,
      host: true,
      presenter: true,
      accountId: account?.id || account?._id || null,
    });
    setRoomJoined(true);
  };

  const handleJoinSubmit = (e) => {
    e.preventDefault();
    if (!joinName.trim() || !joinRoomId.trim()) {
      toast.error("Please enter your name and Room ID!");
      return;
    }

    setUser({
      roomId: joinRoomId.trim(),
      userId: uuid(),
      userName: joinName.trim(),
      host: false,
      presenter: false,
      accountId: account?.id || account?._id || null,
    });
    setRoomJoined(true);
  };

  return (
    <div className="wb-page">
      {/* Decorative doodles — purely visual, hidden on small screens */}
      <svg className="wb-doodle wb-doodle-scribble" viewBox="0 0 80 40" fill="none">
        <path d="M2 20c8-16 16 16 24 0s16 16 24 0 16 16 26 0" stroke="#6d28d9" strokeWidth="3" strokeLinecap="round" />
      </svg>
      <svg className="wb-doodle wb-doodle-circle" viewBox="0 0 60 60" fill="none">
        <circle cx="30" cy="30" r="24" stroke="#0891b2" strokeWidth="3" strokeDasharray="6 8" strokeLinecap="round" />
      </svg>
      <svg className="wb-doodle wb-doodle-star" viewBox="0 0 40 40" fill="none">
        <path d="M20 2l4 12 12 4-12 4-4 12-4-12-12-4 12-4z" stroke="#a78bfa" strokeWidth="2.5" strokeLinejoin="round" />
      </svg>

      {/* Navigation */}
      <nav className="wb-nav">
        <div className="wb-nav-content">
          <div className="wb-logo">
            <svg className="wb-logo-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path d="M12 19l7-7 3 3-7 7-3-3z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
              <path d="M18 13l-1.5-7.5L2 2l3.5 14.5L13 18l5-5z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            <div className="wb-logo-text-group">
              <span className="wb-logo-text">Whiteboard</span>
              <svg className="wb-logo-underline" viewBox="0 0 100 8" fill="none">
                <path d="M2 5c14-6 20 4 32 0s20-6 32 0 20 4 32 0" strokeWidth="2.5" strokeLinecap="round" />
              </svg>
            </div>
          </div>

          {account ? (
            <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
              <span style={{ fontSize: "0.85rem", color: "#64748b", fontWeight: 600 }}>
                {account.name} · {account.email}
              </span>
              <button
                type="button"
                onClick={onLogout}
                style={{
                  background: "none", border: "1px solid #e2e8f0", borderRadius: "0.5rem",
                  padding: "0.35rem 0.75rem", fontSize: "0.8rem", fontWeight: 700,
                  color: "#64748b", cursor: "pointer",
                }}
              >
                Log out
              </button>
            </div>
          ) : (
            <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
              <button
                type="button"
                onClick={onLoginClick}
                style={{
                  background: "none", border: "none", fontSize: "0.9rem", fontWeight: 600,
                  color: "#64748b", cursor: "pointer", padding: "0.5rem",
                }}
              >
                Log in
              </button>
              <button
                type="button"
                onClick={onSignupClick}
                style={{
                  background: "#0891b2", border: "none", borderRadius: "0.5rem",
                  padding: "0.4rem 1rem", fontSize: "0.9rem", fontWeight: 600,
                  color: "white", cursor: "pointer",
                }}
              >
                Sign up
              </button>
            </div>
          )}
        </div>
      </nav>

      {/* Hero Section */}
      <div className="wb-hero">
        <div className="wb-container">
          <div className="wb-badge-wrapper">
            <div className="wb-badge">
              <span className="wb-badge-dot" />
              Real-time Collaboration
            </div>
          </div>

          <h1 className="wb-title">
            Draw Together. Create Magic.
          </h1>

          <p className="wb-subtitle">
            The most elegant whiteboard platform for teams, educators, and creators.
            Unlock real-time collaboration—no latency, no credit card needed.
          </p>

          <div className="wb-benefits">
            <div className="wb-benefit">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Live sync, no refresh needed
            </div>
            <div className="wb-benefit">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <path d="M9 12l2 2 4-4" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                <circle cx="12" cy="12" r="10" strokeWidth="2" />
              </svg>
              Free forever
            </div>
            <div className="wb-benefit">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <rect x="4" y="2" width="16" height="20" rx="2" strokeWidth="2" />
                <path d="M10 18h4" strokeWidth="2" strokeLinecap="round" />
              </svg>
              Works on desktop, tablet & phone
            </div>
          </div>

          {prefilled && (
            <div className="wb-prefill-note">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              We filled in the Room ID from your invite link
            </div>
          )}

          {/* Cards Grid */}
          <div className="wb-cards-grid">
            {/* Create Room Card */}
            <div
              className={`wb-card ${hoveredCard === 'create' ? 'wb-card-hovered' : ''}`}
              onMouseEnter={() => setHoveredCard('create')}
              onMouseLeave={() => setHoveredCard(null)}
            >
              <div className="wb-card-glow wb-glow-orange"></div>

              <div className="wb-card-content">
                <div className="wb-card-icon wb-icon-orange">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                    <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </div>

                <h3 className="wb-card-title">Create Room</h3>
                <p className="wb-card-desc">Start a new collaboration session instantly</p>

                <form className="wb-form" onSubmit={handleCreateSubmit}>
                  <div className="wb-input-group">
                    <label className="wb-label" htmlFor="create-name">Your Name</label>
                    <input
                      id="create-name"
                      type="text"
                      placeholder="Enter your name"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      className="wb-input"
                    />
                  </div>

                  <div className="wb-input-group">
                    <label className="wb-label" htmlFor="create-board-name">
                      Board Name <span style={{ fontWeight: 400, color: "#9ca3af" }}>(optional)</span>
                    </label>
                    <input
                      id="create-board-name"
                      type="text"
                      placeholder="e.g. Project Alpha, College Notes"
                      value={boardName}
                      onChange={(e) => setBoardName(e.target.value)}
                      maxLength={80}
                      className="wb-input"
                    />
                  </div>

                  <div className="wb-input-group">
                    <label className="wb-label">Meeting ID</label>

                    {/* Random vs. custom toggle */}
                    <div style={{ display: "flex", gap: "0.5rem", marginBottom: "0.35rem" }}>
                      <button
                        type="button"
                        onClick={() => handleModeChange("random")}
                        style={{
                          flex: 1, padding: "0.4rem 0.6rem", borderRadius: "0.6rem",
                          border: `1.5px solid ${idMode === "random" ? "#fb923c" : "#e2e8f0"}`,
                          background: idMode === "random" ? "#fff7ed" : "white",
                          color: idMode === "random" ? "#ea580c" : "#64748b",
                          fontWeight: 700, fontSize: "0.78rem", cursor: "pointer",
                        }}
                      >
                        Auto-generate
                      </button>
                      <button
                        type="button"
                        onClick={() => handleModeChange("custom")}
                        style={{
                          flex: 1, padding: "0.4rem 0.6rem", borderRadius: "0.6rem",
                          border: `1.5px solid ${idMode === "custom" ? "#fb923c" : "#e2e8f0"}`,
                          background: idMode === "custom" ? "#fff7ed" : "white",
                          color: idMode === "custom" ? "#ea580c" : "#64748b",
                          fontWeight: 700, fontSize: "0.78rem", cursor: "pointer",
                        }}
                      >
                        Create my own
                      </button>
                    </div>

                    <div className="wb-room-id-group">
                      <input
                        id="create-room-id"
                        type="text"
                        value={roomId}
                        readOnly={idMode === "random"}
                        onChange={(e) => idMode === "custom" && handleCustomIdChange(e.target.value)}
                        placeholder={idMode === "custom" ? "e.g. friday-standup" : ""}
                        className={`wb-input wb-room-id ${idMode === "random" ? "wb-input--readonly" : ""}`}
                      />
                      {idMode === "random" && (
                        <button
                          type="button"
                          onClick={() => setRoomId(uuid())}
                          className="wb-btn-icon wb-btn-generate"
                          title="Generate new ID"
                          aria-label="Generate new room ID"
                        >
                          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                            <path d="M21 12a9 9 0 1 1-3-6.7M21 3v6h-6" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                          </svg>
                        </button>
                      )}
                      <button
                        type="button"
                        onClick={handleCopy}
                        className="wb-btn-icon wb-btn-copy"
                        title="Copy Meeting ID"
                        aria-label="Copy meeting ID"
                        disabled={!roomId.trim()}
                      >
                        {copied ? (
                          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                            <path d="M20 6L9 17l-5-5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
                          </svg>
                        ) : (
                          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                            <rect x="9" y="9" width="12" height="12" rx="2" strokeWidth="2" />
                            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" strokeWidth="2" />
                          </svg>
                        )}
                      </button>
                    </div>
                    {customIdError && <span className="wb-inline-error">{customIdError}</span>}
                    <span style={{ fontSize: "0.75rem", color: "#94a3b8" }}>
                      This exact ID is what you'll share — anyone who enters it lands in the same room.
                    </span>
                  </div>

                  <button type="submit" className="wb-btn-primary wb-btn-orange">
                    <span>Create Room</span>
                    <svg className="wb-arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <path d="M5 12h14M12 5l7 7-7 7" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </button>
                </form>
              </div>
            </div>

            {/* Join Room Card */}
            <div
              className={`wb-card ${hoveredCard === 'join' ? 'wb-card-hovered' : ''} ${prefilled ? 'wb-card-highlighted' : ''}`}
              onMouseEnter={() => setHoveredCard('join')}
              onMouseLeave={() => setHoveredCard(null)}
            >
              <div className="wb-card-glow wb-glow-rose"></div>

              <div className="wb-card-content">
                <div className="wb-card-icon wb-icon-rose">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor">
                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                    <circle cx="9" cy="7" r="4" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                    <path d="M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </div>

                <h3 className="wb-card-title">Join Room</h3>
                <p className="wb-card-desc">Connect to an existing session</p>

                <form className="wb-form" onSubmit={handleJoinSubmit}>
                  <div className="wb-input-group">
                    <label className="wb-label" htmlFor="join-name">Your Name</label>
                    <input
                      id="join-name"
                      type="text"
                      placeholder="Enter your name"
                      value={joinName}
                      onChange={(e) => setJoinName(e.target.value)}
                      className="wb-input"
                    />
                  </div>

                  <div className="wb-input-group">
                    <label className="wb-label" htmlFor="join-room-id">Room ID</label>
                    <input
                      id="join-room-id"
                      type="text"
                      placeholder="Enter room ID"
                      value={joinRoomId}
                      onChange={(e) => setJoinRoomId(e.target.value)}
                      className="wb-input wb-monospace"
                    />
                  </div>

                  <button type="submit" className="wb-btn-primary wb-btn-rose">
                    <span>Join Room</span>
                    <svg className="wb-arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <path d="M5 12h14M12 5l7 7-7 7" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </button>
                </form>
              </div>
            </div>
          </div>

          {/* Footer Text */}
          <p className="wb-footer-text">
            No credit card required • Free forever • Start collaborating instantly
          </p>
        </div>
      </div>
    </div>
  );
};

export default JoinCreateRoom;